inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.1
  TargetRailsVersion: 7.0
  Exclude:
    - gemfiles/vendor/bundle/**/*

Style/HashSyntax:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - spec/support/db_schema.rb

Metrics/BlockLength:
  IgnoredMethods:
    - describe
    - it
