os: linux
dist: xenial
cache: bundler
language: ruby
services:
  - mysql
rvm:
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - ruby-head

jobs:
  allow_failures:
    - rvm: 3.0
    - rvm: ruby-head
    - gemfile: gemfiles/Gemfile.rails-edge  # Unsupported
  exclude:
    - rvm: 3.0
      gemfile: gemfiles/Gemfile.rails-5.0.x # Unsupported
    - rvm: 3.0
      gemfile: gemfiles/Gemfile.rails-5.1.x # Unsupported
    - rvm: 3.0
      gemfile: gemfiles/Gemfile.rails-6.0.x # Unsupported

before_install: gem install bundler
gemfile:
  - gemfiles/Gemfile.rails-5.0.x
  - gemfiles/Gemfile.rails-5.1.x
  - gemfiles/Gemfile.rails-5.2.x
  - gemfiles/Gemfile.rails-6.0.x
  - gemfiles/Gemfile.rails-6.1.x
  - gemfiles/Gemfile.rails-edge

script:
  - bundle exec rspec
  - if [ $TRAVIS_RUBY_VERSION != 2.3 ]; then bundle exec rubocop; fi
